"""Full Q3 causal rolling-horizon evaluation and result3 writer.

The executable follows section 13 of 题目分析报告.md.  It selects the load
update switch and residual quantile on January only, freezes them, evaluates
M0--M3 over 2025-02-01..12-31, applies the predeclared economic gate at each
release, and writes the official result3 template only from a strategy that
passes the upgrade gate.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import platform
import shutil
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
import openpyxl
import pandas as pd
import scipy
from scipy import sparse
from scipy.optimize import linprog

PROGRAM_DIR = Path(__file__).resolve().parent
ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "Q2" / "program"))

import q2_pipeline_v1 as core
import q2_v2_compatible as q2full
import q3_pipeline_v2 as q3p1


OUT = ROOT / "Q3" / "v2" / "result"
# This log is generated by the Q2-v2-compatible continuous January bridge.
Q2_LOG = ROOT / "Q3" / "v2" / "result" / "q2_v2_continuous_warmup_log.csv"
TEMPLATE = ROOT / "附件" / "附件5" / "result3.xlsx"
FIRST_DAY = 31
LAST_DAY = 364
ALPHAS = (0.50, 0.60, 0.65, 0.70, 0.75)
CORRECTIONS = (False, True)
RELEASE_SETS = {
    "M0": (),
    "M1": (6,),
    "M2": (6, 12),
    "M3": (6, 12, 18),
}
BOOTSTRAP_SEED = 20260912
BOOTSTRAP_REPS = 2000
MIN_REL_SAVING = 0.002
TOL = 1e-5


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


@dataclass(frozen=True)
class Config:
    alpha: float
    load_correction: bool

    @property
    def name(self) -> str:
        return f"corr{int(self.load_correction)}_a{self.alpha:.2f}"


@dataclass
class PlanRecord:
    day_index: int
    q0: np.ndarray
    qfinal: np.ndarray
    predicted_start_soc: float
    realized_start_soc: float
    release_forecasts: Dict[int, q3p1.ReleaseForecast]
    confirmation_count: np.ndarray
    q0_lp_residual: float
    q0_solve_seconds: float


class ForecastCache:
    def __init__(
        self,
        dataset: core.Dataset,
        book: q3p1.ForecastBook,
        q2_library: Dict[Tuple[str, str], Dict[int, core.Forecast]],
    ) -> None:
        self.dataset = dataset
        self.book = book
        self.q2_library = q2_library
        self.cache: Dict[Tuple[int, int, bool], q3p1.ReleaseForecast] = {}

    def get(self, day: int, release: int, correction: bool) -> q3p1.ReleaseForecast:
        key = (day, release, correction)
        if key not in self.cache:
            self.cache[key] = q3p1.build_release_forecast(
                self.dataset,
                self.book,
                self.q2_library,
                day,
                release,
                use_load_correction=correction,
            )
        return self.cache[key]


class CurveCache:
    def __init__(
        self,
        dataset: core.Dataset,
        q2_library: Dict[Tuple[str, str], Dict[int, core.Forecast]],
    ) -> None:
        self.dataset = dataset
        self.q2_library = q2_library
        self.cache: Dict[Tuple[int, float], Tuple[np.ndarray, np.ndarray]] = {}

    def get(self, day: int, alpha: float) -> Tuple[np.ndarray, np.ndarray]:
        key = (day, float(alpha))
        if key not in self.cache:
            cfg = q2full.StrategyConfig(
                "Q3_terminal_value",
                q3p1.LOAD_MODEL,
                q3p1.PV_MODEL_FOR_Q2_VALUE,
                float(alpha),
                "pwl",
            )
            curve = q2full.next_day_value_curve(
                self.dataset, day, cfg, self.q2_library
            )
            if not curve["monotone"] or not curve["convex"]:
                raise AssertionError(f"{self.dataset.dates[day].date()}价值曲线形状失败")
            self.cache[key] = (
                np.asarray(curve["grid"], dtype=float),
                np.asarray(curve["values"], dtype=float),
            )
        grid, values = self.cache[key]
        return grid.copy(), values.copy()


def residual_pools(
    dataset: core.Dataset,
    cache: ForecastCache,
    day: int,
    release: int,
    steps: np.ndarray,
    correction: bool,
    risk_days: int,
    gate_days: int,
) -> Tuple[np.ndarray, np.ndarray, List[int], List[int]]:
    issue = dataset.dates[day] + pd.Timedelta(hours=release)
    candidates: List[int] = []
    lookback = risk_days + gate_days + 2
    for old in range(max(0, day - lookback), day):
        latest_end = dataset.interval_starts(old)[int(np.max(steps))] + pd.Timedelta(minutes=10)
        if latest_end <= issue:
            candidates.append(old)
    residuals = []
    for old in candidates:
        old_forecast = cache.get(old, release, correction)
        positions = np.searchsorted(old_forecast.steps, steps)
        prediction = old_forecast.net_kwh[positions]
        actual = dataset.load_kwh[old, steps] - dataset.pv_kwh[old, steps]
        residuals.append(actual - prediction)
    if not residuals:
        width = len(steps)
        return np.zeros((0, width)), np.zeros((0, width)), [], []
    matrix = np.vstack(residuals)
    nr = min(risk_days, len(matrix))
    risk = matrix[-nr:]
    gate_end = len(matrix) - nr
    gate_start = max(0, gate_end - gate_days)
    return (
        risk,
        matrix[gate_start:gate_end],
        candidates[-nr:],
        candidates[gate_start:gate_end],
    )


def solve_adjustment(
    q0: np.ndarray,
    forecast: q3p1.ReleaseForecast,
    margin: np.ndarray,
    start_soc: float,
    block: Tuple[int, int],
    price: np.ndarray,
    settlement: str,
    terminal_curve: Optional[Tuple[np.ndarray, np.ndarray]],
    hard_anchor: Optional[float] = None,
    perfect_net: Optional[np.ndarray] = None,
) -> Dict[str, object]:
    steps = forecast.steps
    n = len(steps)
    ou, or_, oc, od, oh, ow = 0, n, 2 * n, 3 * n, 4 * n, 5 * n
    oe = 6 * n
    use_pwl = terminal_curve is not None
    oz = oe + n + 1
    nvar = oz + 1 if use_pwl else oe + n + 1
    obj = np.zeros(nvar)
    p = price[steps]
    obj[ou:ou + n] = 1.5 * p
    obj[or_:or_ + n] = -0.5 * p if settlement == "B" else 0.5 * p
    obj[oc:oc + n] = core.EPS_THROUGHPUT
    obj[od:od + n] = core.EPS_THROUGHPUT
    obj[oh:oh + n] = 5.0 * p
    if use_pwl:
        obj[oz] = 1.0

    aeq = sparse.lil_matrix((2 * n, nvar))
    beq = np.zeros(2 * n)
    risk_net = perfect_net if perfect_net is not None else forecast.net_kwh + margin
    for k, step in enumerate(steps):
        aeq[k, ou + k] = 1.0
        aeq[k, or_ + k] = -1.0
        aeq[k, oc + k] = -1.0
        aeq[k, od + k] = 1.0
        aeq[k, oh + k] = 1.0
        aeq[k, ow + k] = -1.0
        beq[k] = float(risk_net[k] - q0[step])
        row = n + k
        aeq[row, oe + k] = -1.0
        aeq[row, oe + k + 1] = 1.0
        aeq[row, oc + k] = -core.ETA_CHARGE
        aeq[row, od + k] = 1.0 / core.ETA_DISCHARGE

    aub = None
    bub = None
    if use_pwl:
        grid, values = terminal_curve
        slopes = np.diff(values) / np.diff(grid)
        intercepts = values[:-1] - slopes * grid[:-1]
        aub = sparse.lil_matrix((len(slopes), nvar))
        bub = np.zeros(len(slopes))
        for k, (slope, intercept) in enumerate(zip(slopes, intercepts)):
            aub[k, oe + n] = float(slope)
            aub[k, oz] = -1.0
            bub[k] = -float(intercept)

    bounds: List[Tuple[Optional[float], Optional[float]]] = []
    for step in steps:
        bounds.append((0.0, None) if block[0] <= step < block[1] else (0.0, 0.0))
    for step in steps:
        can_reduce = settlement == "B" and block[0] <= step < block[1]
        bounds.append((0.0, float(q0[step])) if can_reduce else (0.0, 0.0))
    bounds.extend([(0.0, core.STEP_LIMIT_KWH)] * n)
    bounds.extend([(0.0, core.STEP_LIMIT_KWH)] * n)
    bounds.extend([(0.0, None)] * n)
    bounds.extend([(0.0, None)] * n)
    bounds.extend([(core.SOC_MIN_KWH, core.SOC_MAX_KWH)] * (n + 1))
    if use_pwl:
        bounds.append((0.0, None))
    bounds[oe] = (start_soc, start_soc)
    if hard_anchor is not None:
        bounds[oe + n] = (hard_anchor, hard_anchor)

    started = time.perf_counter()
    result = linprog(
        obj,
        A_ub=None if aub is None else aub.tocsr(),
        b_ub=bub,
        A_eq=aeq.tocsr(),
        b_eq=beq,
        bounds=bounds,
        method="highs",
        options={"time_limit": 5.0},
    )
    elapsed = time.perf_counter() - started
    if not result.success:
        if settlement == "A" and result.status == 1:
            # Exact feasible fallback for the sensitivity model: retain q0.
            # This does not affect the B main result and is explicitly counted.
            return {
                "candidate": q0.copy(),
                "u": np.zeros(n),
                "r": np.zeros(n),
                "charge": np.zeros(n),
                "discharge": np.zeros(n),
                "planned_emergency": np.zeros(n),
                "soc": np.full(n + 1, start_soc),
                "max_residual": 0.0,
                "solve_seconds": float(elapsed),
                "fallback_keep_contract": True,
            }
        raise RuntimeError(f"调整LP失败 day={forecast.day_index} release={forecast.release_hour}: {result.message}")
    x = np.asarray(result.x)
    u, r = x[ou:ou + n], x[or_:or_ + n]
    candidate = q0.copy()
    candidate[steps] = q0[steps] + u - r
    eq_res = np.asarray(aeq.tocsr() @ x - beq)
    ub_res = np.asarray([0.0]) if aub is None else np.maximum(np.asarray(aub.tocsr() @ x - bub), 0.0)
    return {
        "candidate": candidate,
        "u": u,
        "r": r,
        "charge": x[oc:oc + n],
        "discharge": x[od:od + n],
        "planned_emergency": x[oh:oh + n],
        "soc": x[oe:oe + n + 1],
        "max_residual": float(max(np.abs(eq_res).max(), ub_res.max())),
        "solve_seconds": float(elapsed),
        "fallback_keep_contract": False,
    }


def block_score(
    q: np.ndarray,
    q0: np.ndarray,
    block: Tuple[int, int],
    start_soc: float,
    forecast_net: np.ndarray,
    scenarios: np.ndarray,
    price: np.ndarray,
    settlement: str,
) -> float:
    start, end = block
    u = np.maximum(q[start:end] - q0[start:end], 0.0)
    r = np.maximum(q0[start:end] - q[start:end], 0.0)
    sign = -0.5 if settlement == "B" else 0.5
    ordinary = float(np.sum(price[start:end] * q0[start:end] + 1.5 * price[start:end] * u + sign * price[start:end] * r))
    samples = scenarios if len(scenarios) else np.zeros((1, end - start))
    lam = core.ETA_DISCHARGE * float(np.median(price))
    scores = []
    for residual in samples:
        soc = float(start_soc)
        emergency_cost = 0.0
        for local, step in enumerate(range(start, end)):
            net = float(forecast_net[local] + residual[local])
            action = core.feedback_step(soc, float(q[step]), max(net, 0.0), max(-net, 0.0))
            soc = float(action["soc_after_kwh"])
            emergency_cost += 5.0 * price[step] * action["emergency_kwh"]
        scores.append(ordinary + emergency_cost - lam * soc)
    return float(np.mean(scores))


def q2_warm_context(dataset: core.Dataset) -> Dict[str, float]:
    if not Q2_LOG.exists():
        raise FileNotFoundError("Q3需要已通过P2的Q2执行日志")
    frame = pd.read_csv(Q2_LOG, parse_dates=["interval_start"])
    row142 = frame.loc[frame["interval_start"] == pd.Timestamp("2025-01-31 23:50")].iloc[0]
    bridge = frame.loc[frame["interval_start"] == pd.Timestamp("2025-02-01 00:00")].iloc[0]
    return {
        "previous_day": 30,
        "soc_midnight": float(row142["soc_after_kwh"]),
        "bridge_q": float(bridge["plan_grid_kwh"]),
        "bridge_load_forecast": float(bridge["load_forecast_kwh"]),
        "bridge_pv_forecast": float(bridge["pv_forecast_kwh"]),
        "bridge_actual_soc_after": float(bridge["soc_after_kwh"]),
    }


def ledger_components(q0: np.ndarray, qfinal: np.ndarray, price: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    u = np.maximum(qfinal - q0, 0.0)
    r = np.maximum(q0 - qfinal, 0.0)
    return price * q0, 1.5 * price * u, -0.5 * price * r, 0.5 * price * r


def repeated_adjustment_ledger_sensitivity(
    plans: Dict[int, PlanRecord],
    price: np.ndarray,
    main_total_yuan: float,
) -> Dict[str, float | int | str]:
    """Stress-test repeated changes while holding every final contract fixed.

    Under settlement B, a monotone sequence from q0 to the same qfinal is
    path-independent. A reversal of ``delta`` (buy delta at one release and
    cancel it at the next) adds ``1.5*p*delta-0.5*p*delta=p*delta``. We use
    ten percent of the observed absolute final adjustment as the reversal
    amount. Steps 71--106 admit one such round trip and steps 107--143 admit
    two; earlier steps have only one confirmation opportunity.

    This is deliberately a ledger sensitivity, not a second control policy:
    qfinal, physical dispatch, emergency purchases, and terminal SOC remain
    identical to the main once-confirm strategy.
    """
    one_reversal_extra = 0.0
    all_opportunities_extra = 0.0
    eligible_intervals = 0
    reversal_energy = 0.0
    for plan in plans.values():
        absolute_change = np.abs(plan.qfinal - plan.q0)
        for step in range(71, 144):
            delta = 0.10 * float(absolute_change[step])
            if delta <= 1e-12:
                continue
            extra = float(price[step]) * delta
            eligible_intervals += 1
            reversal_energy += delta
            one_reversal_extra += extra
            round_trip_count = 1 if step <= 106 else 2
            all_opportunities_extra += round_trip_count * extra
    return {
        "scope": "same-final-contract ledger sensitivity; no physical re-optimization",
        "reversal_fraction_of_observed_adjustment": 0.10,
        "eligible_changed_intervals": eligible_intervals,
        "single_reversal_energy_kwh": reversal_energy,
        "monotone_repeated_total_yuan": float(main_total_yuan),
        "single_reversal_extra_yuan": one_reversal_extra,
        "single_reversal_total_yuan": float(main_total_yuan + one_reversal_extra),
        "all_available_reversals_extra_yuan": all_opportunities_extra,
        "all_available_reversals_total_yuan": float(main_total_yuan + all_opportunities_extra),
    }


def simulate_schedule(
    dataset: core.Dataset,
    cache: ForecastCache,
    curves: CurveCache,
    config: Config,
    schedule: str,
    first_day: int,
    last_day: int,
    warm: Optional[Dict[str, float]] = None,
    settlement: str = "B",
    progress: bool = False,
) -> Tuple[pd.DataFrame, pd.DataFrame, Dict[int, PlanRecord]]:
    allowed = RELEASE_SETS[schedule]
    records: List[Dict[str, object]] = []
    decisions: List[Dict[str, object]] = []
    plans: Dict[int, PlanRecord] = {}
    if warm is None:
        soc_midnight = core.INITIAL_SOC_KWH
        previous: Optional[Dict[str, object]] = None
    else:
        soc_midnight = float(warm["soc_midnight"])
        previous = {
            "day": int(warm["previous_day"]),
            "q0_bridge": float(warm["bridge_q"]),
            "qfinal_bridge": float(warm["bridge_q"]),
            "load_forecast_bridge": float(warm["bridge_load_forecast"]),
            "pv_forecast_bridge": float(warm["bridge_pv_forecast"]),
            "release_used": "Q2_R2_warmup",
        }

    def append_execution(
        plan_day: int,
        step: int,
        q0_value: float,
        qfinal_value: float,
        soc_before: float,
        release_used: object,
    ) -> float:
        action = core.feedback_step(
            soc_before,
            qfinal_value,
            float(dataset.load_kwh[plan_day, step]),
            float(dataset.pv_kwh[plan_day, step]),
        )
        start = dataset.interval_starts(plan_day)[step]
        base, up, refund, penalty = ledger_components(
            np.asarray([q0_value]), np.asarray([qfinal_value]), np.asarray([dataset.price[step]])
        )
        records.append({
            "interval_start": start,
            "interval_end": start + pd.Timedelta(minutes=10),
            "plan_day": dataset.dates[plan_day],
            "natural_day": start.normalize(),
            "step": step,
            "template_label": dataset.template_labels[step],
            "schedule": schedule,
            "alpha": config.alpha,
            "load_correction": config.load_correction,
            "settlement": settlement,
            "release_used": release_used,
            "load_actual_kw": float(dataset.load_kw[plan_day, step]),
            "pv_actual_kw": float(dataset.pv_kw[plan_day, step]),
            "load_actual_kwh": float(dataset.load_kwh[plan_day, step]),
            "pv_actual_kwh": float(dataset.pv_kwh[plan_day, step]),
            "q0_kwh": q0_value,
            "qfinal_kwh": qfinal_value,
            "base_plan_cost_yuan": float(base[0]),
            "up_adjustment_cost_yuan": float(up[0]),
            "down_refund_B_yuan": float(refund[0]),
            "down_penalty_A_yuan": float(penalty[0]),
            "ordinary_cost_B_yuan": float(base[0] + up[0] + refund[0]),
            "ordinary_cost_A_yuan": float(base[0] + up[0] + penalty[0]),
            "actual_emergency_kwh": float(action["emergency_kwh"]),
            "emergency_cost_yuan": float(5.0 * dataset.price[step] * action["emergency_kwh"]),
            "charge_kwh": float(action["charge_kwh"]),
            "discharge_kwh": float(action["discharge_kwh"]),
            "unused_supply_kwh": float(action["unused_supply_kwh"]),
            "soc_before_kwh": soc_before,
            "soc_after_kwh": float(action["soc_after_kwh"]),
            "price_yuan_per_kwh": float(dataset.price[step]),
        })
        return float(action["soc_after_kwh"])

    for day in range(first_day, last_day + 1):
        issue = dataset.dates[day]
        rel0 = cache.get(day, 0, config.load_correction)
        risk0, _, risk0_days, _ = residual_pools(
            dataset, cache, day, 0, rel0.steps, config.load_correction,
            risk_days=core.MAX_RESIDUAL_DAYS, gate_days=0,
        )
        margin0 = np.quantile(risk0, config.alpha, axis=0) if len(risk0) >= core.MIN_RESIDUAL_DAYS else np.zeros(core.N_STEPS)
        if previous is None:
            predicted_start = core.INITIAL_SOC_KWH
        else:
            predicted_start = float(core.feedback_step(
                soc_midnight,
                float(previous["qfinal_bridge"]),
                float(previous["load_forecast_bridge"]),
                float(previous["pv_forecast_bridge"]),
            )["soc_after_kwh"])

        if day == LAST_DAY and last_day == LAST_DAY:
            q0_solution = q2full.solve_plan(
                rel0.net_kwh + margin0,
                dataset.price,
                predicted_start,
                "hard",
                hard_anchor=core.INITIAL_SOC_KWH,
            )
            terminal_curve = None
        else:
            terminal_curve = curves.get(day, config.alpha)
            q0_solution = q2full.solve_plan(
                rel0.net_kwh + margin0,
                dataset.price,
                predicted_start,
                "pwl",
                pwl_curve=terminal_curve,
            )
        q0 = np.asarray(q0_solution["q"]).copy()
        qcurrent = q0.copy()
        qfinal = q0.copy()
        confirmations = np.zeros(core.N_STEPS, dtype=int)

        # The new 00:00 contract is now frozen.  Only now may the previous
        # day's bridge truth be executed.
        if previous is None:
            actual_start = core.INITIAL_SOC_KWH
        else:
            prev_day = int(previous["day"])
            actual_start = append_execution(
                prev_day,
                143,
                float(previous["q0_bridge"]),
                float(previous["qfinal_bridge"]),
                soc_midnight,
                previous["release_used"],
            )
        soc = float(actual_start)
        latest = rel0
        latest_release: object = 0

        def execute(first: int, end: int) -> None:
            nonlocal soc
            for step in range(first, end):
                soc = append_execution(
                    day, step, float(q0[step]), float(qfinal[step]), soc, latest_release
                )

        execute(0, 35)
        for release in (6, 12, 18):
            block = q3p1.BLOCKS[release]
            if release in allowed:
                forecast = cache.get(day, release, config.load_correction)
                latest = forecast
                latest_release = release
                risk, gate, risk_days, gate_days = residual_pools(
                    dataset, cache, day, release, forecast.steps,
                    config.load_correction, risk_days=14, gate_days=14,
                )
                margin = np.quantile(risk, config.alpha, axis=0) if len(risk) >= q3p1.MIN_POOL else np.zeros(len(forecast.steps))
                if day == LAST_DAY and last_day == LAST_DAY:
                    solved = solve_adjustment(
                        q0, forecast, margin, soc, block, dataset.price,
                        settlement, None, hard_anchor=core.INITIAL_SOC_KWH,
                    )
                else:
                    solved = solve_adjustment(
                        q0, forecast, margin, soc, block, dataset.price,
                        settlement, terminal_curve,
                    )
                candidate = np.asarray(solved["candidate"]).copy()
                positions = np.flatnonzero(
                    (forecast.steps >= block[0]) & (forecast.steps < block[1])
                )
                keep_score = block_score(
                    qcurrent, q0, block, soc, forecast.net_kwh[positions],
                    gate[:, positions] if len(gate) else np.zeros((0, len(positions))),
                    dataset.price, settlement,
                )
                new_score = block_score(
                    candidate, q0, block, soc, forecast.net_kwh[positions],
                    gate[:, positions] if len(gate) else np.zeros((0, len(positions))),
                    dataset.price, settlement,
                )
                accepted = bool(len(gate_days) >= q3p1.MIN_POOL and new_score < keep_score - 1e-9)
                if accepted:
                    qcurrent[block[0]:block[1]] = candidate[block[0]:block[1]]
                    qfinal[block[0]:block[1]] = candidate[block[0]:block[1]]
                    confirmations[block[0]:block[1]] += 1
                decisions.append({
                    "day": dataset.dates[day],
                    "issue_time": forecast.issue_time,
                    "schedule": schedule,
                    "release_hour": release,
                    "block_start": block[0],
                    "block_end_exclusive": block[1],
                    "soc_kwh": soc,
                    "accepted": accepted,
                    "keep_score_yuan": keep_score,
                    "new_score_yuan": new_score,
                    "changed_intervals": int(np.count_nonzero(np.abs(candidate[block[0]:block[1]] - q0[block[0]:block[1]]) > 1e-8)) if accepted else 0,
                    "risk_days": len(risk_days),
                    "risk_day_first": dataset.dates[risk_days[0]] if risk_days else pd.NaT,
                    "risk_day_last": dataset.dates[risk_days[-1]] if risk_days else pd.NaT,
                    "gate_days": len(gate_days),
                    "gate_day_first": dataset.dates[gate_days[0]] if gate_days else pd.NaT,
                    "gate_day_last": dataset.dates[gate_days[-1]] if gate_days else pd.NaT,
                    "load_source_max": forecast.load_source_max,
                    "load_correction_source_max": forecast.load_correction_source_max,
                    "anchor_source": forecast.anchor_source,
                    "lp_residual_kwh": solved["max_residual"],
                    "solve_seconds": solved["solve_seconds"],
                    "planned_mutex_violations": int(np.count_nonzero(
                        (np.asarray(solved["charge"]) > TOL)
                        & (np.asarray(solved["discharge"]) > TOL)
                    )),
                    "solver_fallback_keep_contract": bool(solved.get("fallback_keep_contract", False)),
                })
            execute(block[0], block[1] if release != 18 else 143)

        plans[day] = PlanRecord(
            day_index=day,
            q0=q0,
            qfinal=qfinal,
            predicted_start_soc=predicted_start,
            realized_start_soc=actual_start,
            release_forecasts={r: cache.get(day, r, config.load_correction) for r in (0,) + tuple(allowed)},
            confirmation_count=confirmations,
            q0_lp_residual=float(q0_solution["max_residual"]),
            q0_solve_seconds=float(q0_solution["solve_seconds"]),
        )
        bridge_pos = int(np.flatnonzero(latest.steps == 143)[0])
        previous = {
            "day": day,
            "q0_bridge": float(q0[143]),
            "qfinal_bridge": float(qfinal[143]),
            "load_forecast_bridge": float(latest.load_kwh[bridge_pos]),
            "pv_forecast_bridge": float(latest.pv_kwh[bridge_pos]),
            "release_used": latest_release,
        }
        soc_midnight = soc
        if progress and ((day - first_day + 1) % 30 == 0 or day == last_day):
            print(f"PROGRESS {schedule} {dataset.dates[day].date()} plans={day-first_day+1}", flush=True)

    if previous is not None:
        last = int(previous["day"])
        _ = append_execution(
            last, 143, float(previous["q0_bridge"]), float(previous["qfinal_bridge"]),
            soc_midnight, previous["release_used"],
        )
    log = pd.DataFrame(records).sort_values("interval_start", kind="stable").reset_index(drop=True)
    return log, pd.DataFrame(decisions), plans


def summarize(log: pd.DataFrame, first_day: int, last_day: int, dataset: core.Dataset) -> Dict[str, float]:
    start = dataset.dates[first_day] + pd.Timedelta(minutes=10)
    end = dataset.dates[last_day] + pd.Timedelta(days=1, minutes=10)
    frame = log.loc[(log["interval_start"] >= start) & (log["interval_start"] < end)]
    return {
        "intervals": int(len(frame)),
        "q0_kwh": float(frame["q0_kwh"].sum()),
        "qfinal_kwh": float(frame["qfinal_kwh"].sum()),
        "base_plan_cost_yuan": float(frame["base_plan_cost_yuan"].sum()),
        "up_adjustment_cost_yuan": float(frame["up_adjustment_cost_yuan"].sum()),
        "down_refund_B_yuan": float(frame["down_refund_B_yuan"].sum()),
        "down_penalty_A_yuan": float(frame["down_penalty_A_yuan"].sum()),
        "ordinary_cost_B_yuan": float(frame["ordinary_cost_B_yuan"].sum()),
        "ordinary_cost_A_yuan": float(frame["ordinary_cost_A_yuan"].sum()),
        "emergency_kwh": float(frame["actual_emergency_kwh"].sum()),
        "emergency_cost_yuan": float(frame["emergency_cost_yuan"].sum()),
        "total_cash_B_yuan": float((frame["ordinary_cost_B_yuan"] + frame["emergency_cost_yuan"]).sum()),
        "total_cash_A_revaluation_yuan": float((frame["ordinary_cost_A_yuan"] + frame["emergency_cost_yuan"]).sum()),
        "unused_supply_kwh": float(frame["unused_supply_kwh"].sum()),
        "charge_kwh": float(frame["charge_kwh"].sum()),
        "discharge_kwh": float(frame["discharge_kwh"].sum()),
        "soc_min_kwh": float(frame["soc_after_kwh"].min()),
        "soc_max_kwh": float(frame["soc_after_kwh"].max()),
        "start_soc_kwh": float(frame.iloc[0]["soc_before_kwh"]),
        "end_soc_kwh": float(frame.iloc[-1]["soc_after_kwh"]),
    }


def select_config(
    dataset: core.Dataset,
    cache: ForecastCache,
    curves: CurveCache,
) -> Tuple[Config, pd.DataFrame]:
    rows = []
    for correction in CORRECTIONS:
        for alpha in ALPHAS:
            cfg = Config(alpha, correction)
            log, decisions, _ = simulate_schedule(
                dataset, cache, curves, cfg, "M3", 0, 29,
                warm=None, settlement="B", progress=False,
            )
            metrics = summarize(log, 0, 29, dataset)
            asset_cost = metrics["total_cash_B_yuan"] - core.ETA_DISCHARGE * float(np.median(dataset.price)) * metrics["end_soc_kwh"]
            rows.append({
                "alpha": alpha,
                "load_correction": correction,
                "asset_adjusted_cost_yuan": asset_cost,
                "accepted_updates": int(decisions["accepted"].sum()) if len(decisions) else 0,
                **metrics,
            })
            print(f"SELECT {cfg.name} score={asset_cost:.6f}", flush=True)
    table = pd.DataFrame(rows).sort_values(
        ["asset_adjusted_cost_yuan", "emergency_kwh", "alpha", "load_correction"],
        kind="stable",
    ).reset_index(drop=True)
    best = table.iloc[0]
    return Config(float(best["alpha"]), bool(best["load_correction"])), table


def daily_metrics(log: pd.DataFrame) -> pd.DataFrame:
    frame = log.copy()
    frame["asset_adjusted_cost_B_yuan"] = (
        frame["ordinary_cost_B_yuan"] + frame["emergency_cost_yuan"]
    )
    grouped = frame.groupby("plan_day", as_index=False).agg(
        total_cash_B_yuan=("asset_adjusted_cost_B_yuan", "sum"),
        ordinary_cost_B_yuan=("ordinary_cost_B_yuan", "sum"),
        emergency_cost_yuan=("emergency_cost_yuan", "sum"),
        emergency_kwh=("actual_emergency_kwh", "sum"),
        unused_supply_kwh=("unused_supply_kwh", "sum"),
        qfinal_kwh=("qfinal_kwh", "sum"),
        start_soc_kwh=("soc_before_kwh", "first"),
        end_soc_kwh=("soc_after_kwh", "last"),
    )
    lam = core.ETA_DISCHARGE * float(np.median(log["price_yuan_per_kwh"]))
    grouped["asset_adjusted_cost_B_yuan"] = grouped["total_cash_B_yuan"] - lam * (
        grouped["end_soc_kwh"] - grouped["start_soc_kwh"]
    )
    return grouped


def block_bootstrap(diff: np.ndarray, block: int = 7) -> Dict[str, float]:
    rng = np.random.default_rng(BOOTSTRAP_SEED + block)
    n = len(diff)
    starts = np.arange(max(1, n - block + 1))
    means = np.empty(BOOTSTRAP_REPS)
    count = int(np.ceil(n / block))
    for i in range(BOOTSTRAP_REPS):
        sample = np.concatenate([diff[s:s + block] for s in rng.choice(starts, size=count, replace=True)])[:n]
        means[i] = float(np.mean(sample))
    return {
        "mean_daily_saving_yuan": float(np.mean(diff)),
        "ci95_low_yuan_per_day": float(np.quantile(means, 0.025)),
        "ci95_high_yuan_per_day": float(np.quantile(means, 0.975)),
        "block_days": block,
        "reps": BOOTSTRAP_REPS,
    }


def window(log: pd.DataFrame, start: pd.Timestamp, end: pd.Timestamp) -> pd.DataFrame:
    return log.loc[(log["interval_start"] >= start) & (log["interval_start"] < end)].copy()


def emergency_events(frame: pd.DataFrame) -> pd.DataFrame:
    tmp = frame.rename(columns={"actual_emergency_kwh": "emergency_grid_kwh"})
    raw = core.merge_emergency_events(tmp)
    if raw.empty:
        return pd.DataFrame(columns=["date", "start", "end", "time_period", "emergency_kwh", "duration_minutes"])
    raw["date"] = pd.to_datetime(raw["start"]).dt.normalize()
    raw["time_period"] = [
        core.format_event_time(pd.Timestamp(s), pd.Timestamp(e))
        for s, e in zip(raw["start"], raw["end"])
    ]
    raw["duration_minutes"] = (
        pd.to_datetime(raw["end"]) - pd.to_datetime(raw["start"])
    ).dt.total_seconds() / 60.0
    return raw[["date", "start", "end", "time_period", "emergency_kwh", "duration_minutes"]]


def natural_blocks(frame: pd.DataFrame, days: pd.DatetimeIndex) -> pd.DataFrame:
    parts = []
    labels = ("0:00-4:00", "4:00-8:00", "8:00-12:00", "12:00-16:00", "16:00-20:00", "20:00-24:00")
    for day in days:
        one = window(frame, day, day + pd.Timedelta(days=1)).sort_values("interval_start")
        if len(one) != 144:
            raise AssertionError(f"自然日不完整: {day.date()} {len(one)}")
        for block, label in enumerate(labels):
            part = one.iloc[block * 24:(block + 1) * 24]
            parts.append({
                "natural_day": day,
                "block": label,
                "charge_kwh": float(part["charge_kwh"].sum()),
                "discharge_kwh": float(part["discharge_kwh"].sum()),
                "interval_count": len(part),
            })
    return pd.DataFrame(parts)


def copy_style(source: openpyxl.cell.Cell, target: openpyxl.cell.Cell) -> None:
    target._style = copy.copy(source._style)
    target.font = copy.copy(source.font)
    target.fill = copy.copy(source.fill)
    target.border = copy.copy(source.border)
    target.alignment = copy.copy(source.alignment)
    target.protection = copy.copy(source.protection)
    target.number_format = source.number_format


def write_result3(
    dataset: core.Dataset,
    plans: Dict[int, PlanRecord],
    log: pd.DataFrame,
    blocks: pd.DataFrame,
    events: pd.DataFrame,
) -> Tuple[Path, Dict[str, object]]:
    OUT.mkdir(parents=True, exist_ok=True)
    output = OUT / "result3.xlsx"
    shutil.copy2(TEMPLATE, output)
    wb = openpyxl.load_workbook(output)
    plan_ws = wb["计划购电量"]
    adjust_ws = wb["调整购电量"]
    days = dataset.dates[FIRST_DAY:LAST_DAY + 1]
    for row, day_index in enumerate(range(FIRST_DAY, LAST_DAY + 1), start=2):
        plan = plans[day_index]
        base, up, refund, _ = ledger_components(plan.q0, plan.qfinal, dataset.price)
        for ws, values, cost in (
            (plan_ws, plan.q0, float(np.dot(dataset.price, plan.q0))),
            (adjust_ws, plan.qfinal, float(np.sum(base + up + refund))),
        ):
            ws.cell(row, 1, dataset.dates[day_index].to_pydatetime())
            for col, value in enumerate(values, start=2):
                ws.cell(row, col, float(value))
            ws.cell(row, 146, float(np.sum(values)))
            ws.cell(row, 147, cost)

    storage = wb["充放电量"]
    storage_styles = [[copy.copy(storage.cell(r, c)) for c in range(1, 7)] for r in range(2, 8)]
    storage.delete_rows(2, storage.max_row - 1)
    for day_offset, day in enumerate(days):
        part = blocks.loc[blocks["natural_day"] == day]
        natural = window(log, day, day + pd.Timedelta(days=1)).sort_values("interval_start")
        if len(part) != 6 or len(natural) != 144:
            raise AssertionError(f"储能输出日不完整: {day.date()}")
        for block_index, (_, item) in enumerate(part.iterrows()):
            row = 2 + day_offset * 6 + block_index
            for col in range(1, 7):
                copy_style(storage_styles[block_index][col - 1], storage.cell(row, col))
            storage.cell(row, 1, day.to_pydatetime() if block_index == 0 else None)
            storage.cell(row, 2, item["block"])
            storage.cell(row, 3, float(item["charge_kwh"]))
            storage.cell(row, 4, float(item["discharge_kwh"]))
            storage.cell(row, 5, "0:00" if block_index == 0 else ("24:00" if block_index == 1 else None))
            storage.cell(row, 6, float(natural.iloc[0]["soc_before_kwh"]) if block_index == 0 else (float(natural.iloc[-1]["soc_after_kwh"]) if block_index == 1 else None))

    emergency = wb["紧急购电量"]
    emergency_styles = [[copy.copy(emergency.cell(r, c)) for c in range(1, 4)] for r in range(2, 5)]
    emergency.delete_rows(2, emergency.max_row - 1)
    rows = events.copy().reset_index(drop=True)
    if rows.empty:
        rows = pd.DataFrame([{"date": days[0], "time_period": None, "emergency_kwh": 0.0}])
    previous_date = None
    for i, item in rows.iterrows():
        row = 2 + i
        for col in range(1, 4):
            copy_style(emergency_styles[i % 3][col - 1], emergency.cell(row, col))
        date = pd.Timestamp(item["date"])
        emergency.cell(row, 1, date.to_pydatetime() if previous_date != date else None)
        emergency.cell(row, 2, item["time_period"])
        emergency.cell(row, 3, float(item["emergency_kwh"]))
        previous_date = date
    wb.save(output)

    # Random cell access is intentionally done in normal mode.  In openpyxl
    # read-only streaming mode, thousands of ws.cell(r,c) calls repeatedly
    # rescan the XML and turn this audit into an hours-long operation.
    check = openpyxl.load_workbook(output, data_only=False, read_only=False)
    plan_read = np.asarray([[check["计划购电量"].cell(r, c).value for c in range(2, 146)] for r in range(2, 336)], dtype=float)
    final_read = np.asarray([[check["调整购电量"].cell(r, c).value for c in range(2, 146)] for r in range(2, 336)], dtype=float)
    expected_plan = np.vstack([plans[d].q0 for d in range(FIRST_DAY, LAST_DAY + 1)])
    expected_final = np.vstack([plans[d].qfinal for d in range(FIRST_DAY, LAST_DAY + 1)])
    plan_daily_amount = np.asarray([check["计划购电量"].cell(r, 146).value for r in range(2, 336)], dtype=float)
    final_daily_amount = np.asarray([check["调整购电量"].cell(r, 146).value for r in range(2, 336)], dtype=float)
    plan_daily_cost = np.asarray([check["计划购电量"].cell(r, 147).value for r in range(2, 336)], dtype=float)
    final_daily_cost = np.asarray([check["调整购电量"].cell(r, 147).value for r in range(2, 336)], dtype=float)
    exp_plan_cost = expected_plan @ dataset.price
    exp_final_cost = []
    for d in range(FIRST_DAY, LAST_DAY + 1):
        base, up, refund, _ = ledger_components(plans[d].q0, plans[d].qfinal, dataset.price)
        exp_final_cost.append(float(np.sum(base + up + refund)))
    st = check["充放电量"]
    storage_charge = np.asarray([st.cell(r, 3).value for r in range(2, 2 + 334 * 6)], dtype=float)
    storage_discharge = np.asarray([st.cell(r, 4).value for r in range(2, 2 + 334 * 6)], dtype=float)
    readback = {
        "sheet_names": check.sheetnames,
        "plan_rows": check["计划购电量"].max_row - 1,
        "adjust_rows": check["调整购电量"].max_row - 1,
        "storage_rows": st.max_row - 1,
        "placeholder_count": sum(1 for ws in check.worksheets for row in ws.iter_rows() for cell in row if cell.value == "⁝"),
        "plan_max_diff_kwh": float(np.max(np.abs(plan_read - expected_plan))),
        "adjust_max_diff_kwh": float(np.max(np.abs(final_read - expected_final))),
        "plan_amount_max_diff_kwh": float(np.max(np.abs(plan_daily_amount - expected_plan.sum(axis=1)))),
        "adjust_amount_max_diff_kwh": float(np.max(np.abs(final_daily_amount - expected_final.sum(axis=1)))),
        "plan_cost_max_diff_yuan": float(np.max(np.abs(plan_daily_cost - exp_plan_cost))),
        "adjust_cost_max_diff_yuan": float(np.max(np.abs(final_daily_cost - np.asarray(exp_final_cost)))),
        "storage_charge_max_diff_kwh": float(np.max(np.abs(storage_charge - blocks["charge_kwh"].to_numpy(float)))),
        "storage_discharge_max_diff_kwh": float(np.max(np.abs(storage_discharge - blocks["discharge_kwh"].to_numpy(float)))),
    }
    return output, readback


def audit_strategy(
    dataset: core.Dataset,
    log: pd.DataFrame,
    decisions: pd.DataFrame,
    plans: Dict[int, PlanRecord],
    schedule: str,
) -> Dict[str, object]:
    wp_start = dataset.dates[FIRST_DAY] + pd.Timedelta(minutes=10)
    wp_end = dataset.dates[LAST_DAY] + pd.Timedelta(days=1, minutes=10)
    wp = window(log, wp_start, wp_end)
    balance = (
        log["qfinal_kwh"] + log["pv_actual_kwh"] + log["discharge_kwh"]
        + log["actual_emergency_kwh"] - log["load_actual_kwh"]
        - log["charge_kwh"] - log["unused_supply_kwh"]
    ).to_numpy(float)
    state = (
        log["soc_after_kwh"] - log["soc_before_kwh"]
        - core.ETA_CHARGE * log["charge_kwh"]
        + log["discharge_kwh"] / core.ETA_DISCHARGE
    ).to_numpy(float)
    starts = pd.DatetimeIndex(log["interval_start"])
    ends = pd.DatetimeIndex(log["interval_end"])
    continuity = float(np.max(np.abs(
        log["soc_before_kwh"].to_numpy(float)[1:]
        - log["soc_after_kwh"].to_numpy(float)[:-1]
    )))
    arrays_independent = all(
        not np.shares_memory(plan.q0, plan.qfinal)
        for plan in plans.values()
    )
    one_confirmation = all(plan.confirmation_count.max() <= 1 for plan in plans.values())
    frozen_early = all(np.allclose(plan.q0[:35], plan.qfinal[:35]) for plan in plans.values())
    expected_decisions = len(plans) * len(RELEASE_SETS[schedule])
    history_causal = True
    pools_disjoint = True
    if len(decisions):
        history_causal = bool(all(
            (pd.isna(r.load_source_max) or pd.Timestamp(r.load_source_max) <= pd.Timestamp(r.issue_time))
            and (pd.isna(r.load_correction_source_max) or pd.Timestamp(r.load_correction_source_max) <= pd.Timestamp(r.issue_time))
            and (pd.isna(r.risk_day_last) or dataset.interval_starts(int(np.flatnonzero(dataset.dates == pd.Timestamp(r.risk_day_last))[0]))[143] + pd.Timedelta(minutes=10) <= pd.Timestamp(r.issue_time))
            for r in decisions.itertuples()
        ))
        pools_disjoint = bool(all(
            pd.isna(r.gate_day_last) or pd.isna(r.risk_day_first)
            or pd.Timestamp(r.gate_day_last) < pd.Timestamp(r.risk_day_first)
            for r in decisions.itertuples()
        ))
    expected_base = log["price_yuan_per_kwh"] * log["q0_kwh"]
    u = np.maximum(log["qfinal_kwh"] - log["q0_kwh"], 0.0)
    r = np.maximum(log["q0_kwh"] - log["qfinal_kwh"], 0.0)
    ledger_error = max(
        float(np.max(np.abs(log["base_plan_cost_yuan"] - expected_base))),
        float(np.max(np.abs(log["up_adjustment_cost_yuan"] - 1.5 * log["price_yuan_per_kwh"] * u))),
        float(np.max(np.abs(log["down_refund_B_yuan"] + 0.5 * log["price_yuan_per_kwh"] * r))),
    )
    scale = max(1.0, float(log[["qfinal_kwh", "load_actual_kwh", "pv_actual_kwh"]].to_numpy().max()))
    checks = {
        "01_wp_334x144": len(wp) == 334 * 144,
        "02_all_intervals_10min": bool(np.all((ends - starts).total_seconds() == 600.0)),
        "03_no_duplicate_or_gap": bool(not starts.duplicated().any() and np.all(starts[1:].asi8 == ends[:-1].asi8)),
        "04_energy_balance": bool(np.max(np.abs(balance)) <= TOL),
        "05_soc_balance": bool(np.max(np.abs(state)) <= TOL),
        "06_normalized_residual": bool(max(np.max(np.abs(balance)), np.max(np.abs(state))) / scale <= 1e-8),
        "07_soc_bounds": bool(log["soc_before_kwh"].min() >= core.SOC_MIN_KWH - TOL and log["soc_after_kwh"].max() <= core.SOC_MAX_KWH + TOL),
        "08_power_bounds": bool(log[["charge_kwh", "discharge_kwh"]].to_numpy().max() <= core.STEP_LIMIT_KWH + TOL),
        "09_actual_mutex": bool(not ((log["charge_kwh"] > TOL) & (log["discharge_kwh"] > TOL)).any()),
        "10_arrays_separate": arrays_independent,
        "11_one_confirmation": one_confirmation,
        "12_early_block_frozen": frozen_early,
        "13_decision_count": len(decisions) == expected_decisions,
        "14_sources_causal": history_causal,
        "15_risk_gate_disjoint": pools_disjoint,
        "16_adjustment_lp_residual": bool(len(decisions) == 0 or (decisions["lp_residual_kwh"] <= TOL).all()),
        "17_planned_mutex": bool(len(decisions) == 0 or (decisions["planned_mutex_violations"] == 0).all()),
        "18_q0_lp_residual": bool(max(p.q0_lp_residual for p in plans.values()) <= TOL),
        "19_ledger_identity": ledger_error <= TOL,
        "20_emergency_never_charges": bool(not ((log["actual_emergency_kwh"] > TOL) & (log["charge_kwh"] > TOL)).any()),
        "21_continuous_soc": continuity <= TOL,
        "22_nonnegative_contracts": bool(log[["q0_kwh", "qfinal_kwh", "actual_emergency_kwh"]].to_numpy().min() >= -TOL),
    }
    return {
        "status": "PASS" if all(checks.values()) else "FAIL",
        "checks": checks,
        "metrics": {
            "max_energy_residual_kwh": float(np.max(np.abs(balance))),
            "max_soc_residual_kwh": float(np.max(np.abs(state))),
            "normalized_residual": float(max(np.max(np.abs(balance)), np.max(np.abs(state))) / scale),
            "soc_continuity_error_kwh": continuity,
            "ledger_max_error_yuan": ledger_error,
            "q0_lp_p95_seconds": float(np.quantile([p.q0_solve_seconds for p in plans.values()], 0.95)),
            "update_lp_p95_seconds": float(np.quantile(decisions["solve_seconds"], 0.95)) if len(decisions) else 0.0,
        },
    }


def release_time_price_revaluation(
    plans: Dict[int, PlanRecord], dataset: core.Dataset, emergency_cost: float
) -> Dict[str, float]:
    base = up = refund = 0.0
    for plan in plans.values():
        base += float(np.dot(dataset.price, plan.q0))
        for release, (start, end) in q3p1.BLOCKS.items():
            p_release = float(dataset.price[start])
            u = np.maximum(plan.qfinal[start:end] - plan.q0[start:end], 0.0)
            r = np.maximum(plan.q0[start:end] - plan.qfinal[start:end], 0.0)
            up += 1.5 * p_release * float(u.sum())
            refund += -0.5 * p_release * float(r.sum())
    return {
        "base_plan_cost_yuan": base,
        "up_adjustment_cost_yuan": up,
        "down_refund_B_yuan": refund,
        "emergency_cost_yuan": emergency_cost,
        "total_cash_yuan": base + up + refund + emergency_cost,
    }


def run_full(skip_selection: bool = False) -> Dict[str, object]:
    OUT.mkdir(parents=True, exist_ok=True)
    started = time.perf_counter()
    dataset = core.load_dataset()
    book = q3p1.load_forecast_book(dataset)
    combo = (q3p1.LOAD_MODEL, q3p1.PV_MODEL_FOR_Q2_VALUE)
    q2_library = q2full.build_forecast_library(dataset, [combo])
    forecast_cache = ForecastCache(dataset, book, q2_library)
    curve_cache = CurveCache(dataset, q2_library)

    if skip_selection:
        selected = Config(0.65, True)
        selection = pd.DataFrame([{"alpha": 0.65, "load_correction": True, "note": "debug_skip_selection"}])
    else:
        selected, selection = select_config(dataset, forecast_cache, curve_cache)
    selection.to_csv(OUT / "q3_january_selection.csv", index=False, encoding="utf-8-sig")
    print(f"SELECTED alpha={selected.alpha} correction={selected.load_correction}", flush=True)

    warm = q2_warm_context(dataset)
    logs: Dict[str, pd.DataFrame] = {}
    decision_sets: Dict[str, pd.DataFrame] = {}
    plan_sets: Dict[str, Dict[int, PlanRecord]] = {}
    summaries: Dict[str, Dict[str, float]] = {}
    audits: Dict[str, Dict[str, object]] = {}
    for schedule in ("M0", "M1", "M2", "M3"):
        log, decisions, plans = simulate_schedule(
            dataset, forecast_cache, curve_cache, selected, schedule,
            FIRST_DAY, LAST_DAY, warm=warm, settlement="B", progress=True,
        )
        logs[schedule], decision_sets[schedule], plan_sets[schedule] = log, decisions, plans
        summaries[schedule] = summarize(log, FIRST_DAY, LAST_DAY, dataset)
        audits[schedule] = audit_strategy(dataset, log, decisions, plans, schedule)
        log.to_csv(OUT / f"q3_{schedule}_execution_log.csv", index=False, encoding="utf-8-sig")
        decisions.to_csv(OUT / f"q3_{schedule}_decisions.csv", index=False, encoding="utf-8-sig")
        print(f"DONE {schedule} cash={summaries[schedule]['total_cash_B_yuan']:.6f} audit={audits[schedule]['status']}", flush=True)

    official_start = dataset.dates[FIRST_DAY] + pd.Timedelta(minutes=10)
    official_end = dataset.dates[LAST_DAY] + pd.Timedelta(days=1, minutes=10)
    daily: Dict[str, pd.DataFrame] = {}
    for name, log in logs.items():
        daily[name] = daily_metrics(window(log, official_start, official_end))
        daily[name]["schedule"] = name
    pd.concat(daily.values(), ignore_index=True).to_csv(
        OUT / "q3_daily_schedule_comparison.csv", index=False, encoding="utf-8-sig"
    )

    lam = core.ETA_DISCHARGE * float(np.median(dataset.price))
    m0_asset = summaries["M0"]["total_cash_B_yuan"] - lam * (
        summaries["M0"]["end_soc_kwh"] - summaries["M0"]["start_soc_kwh"]
    )
    gates: Dict[str, Dict[str, object]] = {}
    for name in ("M1", "M2", "M3"):
        asset = summaries[name]["total_cash_B_yuan"] - lam * (
            summaries[name]["end_soc_kwh"] - summaries[name]["start_soc_kwh"]
        )
        saving = m0_asset - asset
        relative = saving / abs(m0_asset)
        merged = daily["M0"][["plan_day", "asset_adjusted_cost_B_yuan"]].merge(
            daily[name][["plan_day", "asset_adjusted_cost_B_yuan"]],
            on="plan_day", suffixes=("_M0", f"_{name}"), validate="one_to_one",
        )
        diff = merged["asset_adjusted_cost_B_yuan_M0"].to_numpy() - merged[f"asset_adjusted_cost_B_yuan_{name}"].to_numpy()
        boot = block_bootstrap(diff, 7)
        passed = bool(
            audits[name]["status"] == "PASS"
            and relative >= MIN_REL_SAVING
            and boot["ci95_low_yuan_per_day"] > 0.0
            and audits[name]["metrics"]["update_lp_p95_seconds"] < 5.0
        )
        gates[name] = {
            "asset_adjusted_saving_yuan": float(saving),
            "relative_asset_adjusted_saving": float(relative),
            "bootstrap_7day": boot,
            "update_lp_p95_seconds": audits[name]["metrics"]["update_lp_p95_seconds"],
            "passed": passed,
        }
    accepted = next((name for name in ("M3", "M2", "M1") if gates[name]["passed"]), "M0")
    print(f"ACCEPTED {accepted}", flush=True)

    accepted_log = logs[accepted]
    accepted_plans = plan_sets[accepted]
    natural = window(
        accepted_log,
        dataset.dates[FIRST_DAY],
        dataset.dates[LAST_DAY] + pd.Timedelta(days=1),
    )
    blocks = natural_blocks(natural, dataset.dates[FIRST_DAY:LAST_DAY + 1])
    events_wc = emergency_events(natural)
    events_wp = emergency_events(window(accepted_log, official_start, official_end))
    workbook, readback = write_result3(dataset, accepted_plans, accepted_log, blocks, events_wc)
    print("RESULT3_WRITTEN_AND_READ_BACK", flush=True)

    template_ok = bool(
        readback["sheet_names"] == ["计划购电量", "调整购电量", "充放电量", "紧急购电量"]
        and readback["plan_rows"] == 334
        and readback["adjust_rows"] == 334
        and readback["storage_rows"] == 334 * 6
        and readback["placeholder_count"] == 0
        and max(
            readback["plan_max_diff_kwh"], readback["adjust_max_diff_kwh"],
            readback["plan_amount_max_diff_kwh"], readback["adjust_amount_max_diff_kwh"],
            readback["plan_cost_max_diff_yuan"], readback["adjust_cost_max_diff_yuan"],
            readback["storage_charge_max_diff_kwh"], readback["storage_discharge_max_diff_kwh"],
        ) <= TOL
    )

    # A is both a post-hoc stress revaluation and an independently optimized
    # no-down-adjustment policy, as required by the ambiguity contract.
    if accepted == "M0":
        a_summary = summaries[accepted].copy()
        a_audit = audits[accepted]
    else:
        print("START_A_OPTIMIZED_SENSITIVITY", flush=True)
        a_log, a_decisions, a_plans = simulate_schedule(
            dataset, forecast_cache, curve_cache, selected, accepted,
            FIRST_DAY, LAST_DAY, warm=warm, settlement="A", progress=True,
        )
        a_summary = summarize(a_log, FIRST_DAY, LAST_DAY, dataset)
        a_audit = audit_strategy(dataset, a_log, a_decisions, a_plans, accepted)
        a_log.to_csv(OUT / "q3_A_optimized_execution_log.csv", index=False, encoding="utf-8-sig")
        a_decisions.to_csv(OUT / "q3_A_optimized_decisions.csv", index=False, encoding="utf-8-sig")

    transaction_price = release_time_price_revaluation(
        accepted_plans, dataset, summaries[accepted]["emergency_cost_yuan"]
    )
    repeated_adjustment = repeated_adjustment_ledger_sensitivity(
        accepted_plans, dataset.price, summaries[accepted]["total_cash_B_yuan"]
    )
    (OUT / "q3_repeated_adjustment_sensitivity.json").write_text(
        json.dumps(repeated_adjustment, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    oracle = q2full.solve_oracle(
        dataset,
        summaries[accepted]["start_soc_kwh"],
        summaries[accepted]["end_soc_kwh"],
    )

    comparison = pd.DataFrame([
        {"schedule": name, **summaries[name], "accepted_updates": int(decision_sets[name]["accepted"].sum()) if len(decision_sets[name]) else 0}
        for name in ("M0", "M1", "M2", "M3")
    ])
    comparison.to_csv(OUT / "q3_schedule_comparison.csv", index=False, encoding="utf-8-sig")
    monthly = []
    for name, frame in daily.items():
        f = frame.copy()
        f["month"] = pd.to_datetime(f["plan_day"]).dt.to_period("M").astype(str)
        g = f.groupby("month", as_index=False).agg(
            total_cash_B_yuan=("total_cash_B_yuan", "sum"),
            emergency_kwh=("emergency_kwh", "sum"),
            unused_supply_kwh=("unused_supply_kwh", "sum"),
        )
        g["schedule"] = name
        monthly.append(g)
    pd.concat(monthly, ignore_index=True).to_csv(
        OUT / "q3_monthly_information_value.csv", index=False, encoding="utf-8-sig"
    )
    focus_dates = pd.to_datetime(["2025-03-20", "2025-06-21", "2025-09-23", "2025-12-21"])
    window(accepted_log, official_start, official_end).loc[
        lambda x: pd.to_datetime(x["plan_day"]).isin(focus_dates)
    ].to_csv(OUT / "q3_focus_days.csv", index=False, encoding="utf-8-sig")
    blocks.to_csv(OUT / "q3_natural_day_blocks.csv", index=False, encoding="utf-8-sig")
    events_wc.to_csv(OUT / "q3_emergency_events_wc.csv", index=False, encoding="utf-8-sig")
    events_wp.to_csv(OUT / "q3_emergency_events_wp.csv", index=False, encoding="utf-8-sig")

    status = "PASS" if (
        all(a["status"] == "PASS" for a in audits.values())
        and a_audit["status"] == "PASS"
        and template_ok
        and Path(ROOT / "Q3" / "v2" / "result" / "p1" / "q3_p1_summary.json").exists()
    ) else "FAIL"
    result = {
        "status": status,
        "scope": "Q3 full 334-plan-day causal rolling backtest",
        "selected_parameters": {"alpha": selected.alpha, "load_correction": selected.load_correction},
        "accepted_schedule": accepted,
        "schedule_summaries": summaries,
        "upgrade_gates": gates,
        "audits": audits,
        "template_readback": readback,
        "template_ok": template_ok,
        "settlement_sensitivity": {
            "B_main_strategy_A_revaluation_total_yuan": summaries[accepted]["total_cash_A_revaluation_yuan"],
            "A_optimized": a_summary,
            "A_optimized_audit": a_audit,
            "release_time_price_B_revaluation": transaction_price,
            "repeated_adjustment_ledger": repeated_adjustment,
        },
        "perfect_foresight_physical_benchmark": oracle,
        "information_value": {
            "M1_minus_M0_cash_saving_yuan": summaries["M0"]["total_cash_B_yuan"] - summaries["M1"]["total_cash_B_yuan"],
            "M2_minus_M1_cash_saving_yuan": summaries["M1"]["total_cash_B_yuan"] - summaries["M2"]["total_cash_B_yuan"],
            "M3_minus_M2_cash_saving_yuan": summaries["M2"]["total_cash_B_yuan"] - summaries["M3"]["total_cash_B_yuan"],
        },
        "files": {
            "result3": str(workbook),
            "comparison": str(OUT / "q3_schedule_comparison.csv"),
            "daily": str(OUT / "q3_daily_schedule_comparison.csv"),
        },
        "manifest": {
            "inputs": {
                "attachment1": sha256(ROOT / "附件" / "附件1.xlsx"),
                "attachment2": sha256(ROOT / "附件" / "附件2.xlsx"),
                "attachment3": sha256(ROOT / "附件" / "附件3.xlsx"),
                "result3_template": sha256(TEMPLATE),
                "q2_execution_log": sha256(Q2_LOG),
                "analysis": sha256(ROOT / "题目分析报告.md"),
                "terms": sha256(ROOT / "术语表格.md"),
                "q3_p1_summary": sha256(ROOT / "Q3" / "v2" / "result" / "p1" / "q3_p1_summary.json"),
            },
            "code": sha256(Path(__file__)),
            "imported_q3_p1_code": sha256(PROGRAM_DIR / "q3_pipeline_v2.py"),
            "seed": BOOTSTRAP_SEED,
            "python": platform.python_version(),
            "numpy": np.__version__,
            "pandas": pd.__version__,
            "scipy": scipy.__version__,
            "openpyxl": openpyxl.__version__,
            "command": f'"{sys.executable}" Q3/v2/program/q3_full_pipeline_v2.py --mode full',
        },
        "runtime_seconds": time.perf_counter() - started,
    }
    (OUT / "q3_final_summary.json").write_text(
        json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    if status != "PASS":
        raise AssertionError("Q3 full audit failed; inspect q3_final_summary.json")
    print(json.dumps({
        "status": status,
        "selected": result["selected_parameters"],
        "accepted_schedule": accepted,
        "accepted_summary": summaries[accepted],
        "upgrade_gates": gates,
        "runtime_seconds": result["runtime_seconds"],
    }, ensure_ascii=False, indent=2), flush=True)
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["full"], default="full")
    parser.add_argument("--skip-selection", action="store_true")
    args = parser.parse_args()
    run_full(skip_selection=args.skip_selection)


if __name__ == "__main__":
    main()
